on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - uses: buildpacks/github-actions/setup-pack@v5.7.2
        if: ${{ steps.release.outputs.release_created }}
      - name: Build and publish docker image
        if: ${{ steps.release.outputs.release_created }}
        run: pack build \
              ch4s3r/mergeable:${{ steps.release.outputs.tag_name }} \
              -B paketobuildpacks/builder-jammy-tiny \
              -b docker.io/paketobuildpacks/nodejs \
              --publish
